---
- name: Add user to PostgreSQL
  hosts: all
  user: ec2-user
  handlers:
    - name: Restart PostgreSQL
      ansible.builtin.service:
        name: postgresql
        state: restarted
  tasks:
    - name: Create user
      community.postgresql.postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        role_attr_flags: LOGIN
      become: true
      become_user: postgres
    - name: Create database
      community.postgresql.postgresql_db:
        state: present
        name: "{{ db_user }}"
      become: true
      become_user: postgres
    - name: Grant user access to db
      community.postgresql.postgresql_privs:
        login_db: "{{ db_user }}"
        privs: ALL
        type: database
        roles: "{{ db_user }}"
      become: true
      become_user: postgres
    - name: Allow md5 connection for the db user
      community.postgresql.postgresql_pg_hba:
        dest: /var/lib/pgsql/data/pg_hba.conf
        contype: host
        users: "{{ db_user }}"
        databases: all
        method: md5
        source: ::/0
        create: true
      notify: Restart PostgreSQL
